{% set version = "1.22" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparsepp
  version: {{ version|replace("-", "_") }}

source:
  fn: sparsepp_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sparsepp_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sparsepp/sparsepp_{{ version }}.tar.gz
  sha256: 2999b3a393ccac46b1702b6def030360d81ec32735faab42f0c3ae790b2a4171

build:
  number: 1000
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('sparsepp')"  # [not win]
    - "\"%R%\" -e \"library('sparsepp')\""  # [win]

about:
  home: https://cran.r-project.org/package=sparsepp
  license: BSD_3_clause
  summary: Provides interface to 'sparsepp' - fast, memory efficient hash map.  It is derived
    from Google's excellent 'sparsehash' implementation. We believe 'sparsepp' provides
    an unparalleled combination of performance and memory usage,  and will outperform
    your compiler's unordered_map on both counts.  Only Google's 'dense_hash_map' is
    consistently faster, at the cost of much greater  memory usage (especially when
    the final size of the map is not known in advance).
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - CurtLH
