travis:
  secure:
    BINSTAR_TOKEN: cmK0nAnf2Uh/alV2lVGQNqi4CGUB8DjY70LxUkefXKFhh6h0lfk/NypeaewyK9GS/aZqbpvz6cdGIZHieC/wWmQaaPMurFdyLqs8zV16smO/tI3ozODI+fbe1cA0lXFEVuBTQCvaL71ZRzKyyDtHTg4lUoKKbkRghaSWNWfcuBv/fwUYupyn1thVV50LfkaU2iHIZWI+b4aoHBI3kkHirirNho1YFhYDAXQ4dMMAyOhfTXTfTtV9fQllnUafu8gvaaZJ87r3Dp0oalRmNERBZHnS3+NkULsUY6mkQ4CNAOt7dEX5Fyq6e2CweVQ3ECxcWeHCNma8Uej09YazrRt4itOmYbMv1gBwgWDeCASgASkWy/BDHoBD5Luuy9BdskkPEqabVN5AZ1s51sCPGaw5qnnK9kMGZC/oWLGX4KVMhRHlseqbThfduLHaloSkppC2gvwkSzcvNDqJr9P4psuiso+sPV8nRTPq67UcclZh+kfXYbqex3KldzqasRRh2wz7QPsy+f/h12ph0G0NH7ntaT6UF+XzRJGLtAtGVX8jFWLSLC4ktIynvr7eAYAm70ylNSurGNNyCZVrnCLMnwRKRwRslb4Q5urbaByueXuZoFZAZO/vKhXQn/3mbNyQ/0/45bWYpGmbtfoZThJzcIh6+pkvHRVv84ABKCFZnRoik3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
