travis:
  secure:
    BINSTAR_TOKEN: DK5t6wAnYL6i/hWJhs0iyO/uldyANqpx6633pG0AmKqJ+9eu+WoLYXv01QSAsNx7CZOBs4lvBwu6GxAgPrIS9WaENH7ySELyiJsXJ3EheHkSbHb5HO+mVsJnDiqch+XGIjNvyvltty6/LeQxUbUrTvxX2zEylquUDTB2tewevI932u68vVCaHF61YtYXpRn4fLLOWDfRvAHYF+5vkvjdyie0ykdo68xRlIk96fKQ2hDtpEDvZCI0e0xQqDVxrgJHSrb7qg+gIrLGHPjQoxK9uyjr/g41PUJ/JWJjfyBaSCl+FtqWjYyny+0lMbIGPTrE9Wl/+FInxVevQSDJFiGVv3F1bBf/CITodrVXQIaO0aNc7oZUXg9a4lw5dU1P+OwcApjx4PUKChqaGHB5FW9v85Zn1bUnCRCQ11nJRZOpCo9UDWk+p3YNRezhS4dNCxefeXHmZMZ62gY+2RM6BH4Ec4txqkzgvmr0euqUO06degoY14O+MaKGyqxudQCb1RTorTyICETkmvE692QMIXHLx92CZ4QtfiwznHCYI1DU14CIZyKKghJNmm5T6F8dbQeJJGOzv7YjE3whwDRwLx9G7MbykUQAVHNSJK0KEn6sNnHkKpOT/FlKVl1l/9UeaVOHJ9Fv6ZKzBOhbL/xRstp9kAO0yrehql2MVyvhhOZ/rQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
