travis:
  secure:
    BINSTAR_TOKEN: XQ7lnCcMosvnUpJKzYNjgwXtjC9DAuFjtoh85nIqZCztMhNeJTKtRsE1qlLpeQ1FL5CINTQZtC6/NGzVim5/UONlOIx3ZTm1YlWTUilFQVjGwyOpK23C9iCT98XA+O/jFuiv6bDeWjYKcMn/L393lMNTe4bGZ0nSuxSTualetrOH+z8lw4ck4LLqZMz2P9fq9TK+7smzCbV7N8LCrF9cTQAvCOE6MbSGruCaZEs9I3j5fpCBW2MYaseHpOhNbYtU4t30PxwKUOYqHn/Frn+Q0gDSYZDggH8apb2/OIQJ5184qWoEESyrpzmyeq6Cc/Gwih/OKP8kRG9lcwrQKs10PKQBlw1c9jZlhUlArN36+tkscGaKBEzOYj7CRj7R7ohRf5YOG20CFDlQ1UpZTfFzayBMXFLfuRFtS3IrJamhjShyzzxAwl4Bk0bM4cT4wUnzQ83/zkeanWhg0RnCPFX2Vy6c7h6Bh33qCRLnGhNDYYPoNpB1hJ+6X7myBVXOFD81zPzVXiskOx6R87j0KOis6UuN5GmJaXvvG8iF8yfvvxOoCEvi/LFxaiwGu0vyanJyLswRXcmOyHe430m5NKCzYkF/UFc3W+DIxgKRuwVx5/LUmj/tBmSPU7DKBd1lNIFmhmzuYo11fD9ENTPLySSChAKKqmn/H5rMJudtL5tp1J0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
