travis:
  secure:
    BINSTAR_TOKEN: QH+EmUxSdV52ptgmid5dWdZzWDg6OtZrn3dgab/4GmSinMmTTagD1ehiLfo7CCHWLOjvNj/KjybqPPYcvYNyJejenihX1Z0ocRL79Ii5Qyv4mQjuIcjQJqN3byc32WFLVv6EFwWeywkYvyTBzS9ZRLFzaQjFOaaEQf0552uIbHugelscSY13RnDO/rEJMwckLTYg+zrqQCCuBoqyyTBlTuEthWQq+XveGzF0xM6+8VXiLEjWeAu5mcLHox3eJFvTWYSjMEpECvBhZMspwL4TmGvjqiugqxhYX4xKC5fSSILi+RmlRUjK7Nrm17iHQFsKuPUiPJx/f7lEPGs+YcNyHoT5Wfk3nQzCkMruhirZaRFeR7+6V1pWu4ErkVH7bnA2p7sl2I/pyXN+Jwj4+6ouQ1qQilRcLsrhSlIbU2eocpbkiuTkBJdA2sD2gNj4RTOV9wtxg5Spc8JK8kYayfNpfM5zZAP7nxjUqzFYM2Yp5Wnibqr7XhBSiomvQpKrYH3iLTZSvSga7d87gkf02qKB0/6tjlDmPgeDgeI4Oo9kUJ1WUE6s9PGqJY7YVitsZczrr5JrGrJf3hYgiYw2OSQ8+OdAxt63reaxTcE5E6W5iIwtEebpRDEi75RAqn8NJrSjWqYOCp8yNl7mJShda5oHVOYpIkZLN3krCtMiwOpaoFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
