travis:
  secure:
    BINSTAR_TOKEN: bvh/PI338qwEHHv9lQPKMmWYqYnbbzZN9kosBXlFsddc/JAzffoBKc6TU/mgqpvNsMJJaPiqqsfptR6DwOdZ3W+qX6louiybYsYS1hK8wqG8eFOjgynDy22EZn5g+TT+TEG6JpGxMCP2lG5MopDxp+76B5DTQ66jtj3BN7WUNWnrn6sxsssKvIEwnU7P17pP1VmR0QSz74MWq5SXBMPLRHRqaEknniXHLZlW6nehUPb0dqRElPfntgGIwqQEHvalnDPlMb2UDZ3crXF3dD3dCpUpoGoBqXw+IzwEsMsOBzNgwDaXQo6d4isaL14FCNoqWqFIUFDxzZjKTY7xQoHtLVPL4Gtvy8CcBTAYcaax8AZhEZAVkrJvQl/ZRIAM7Z27swFPGySqpO9jzLeIjM+XF+T8a5OJEH/VEUQIjFAS1wsATsT4GI2GuMBgFPPW4ArdL/WEagaTTNV2dZWjG+Cy3X1TlgQLxCk9zC4vt64BPzvYyHyf04sHmgvDwi7shepUCVNXYrG35zEWiEQRGUj/XpIZwSITb0GEJ1rWaXXcy3JrFdutz/crgVzDcy9+TkxwcvfZ3xXKR4NYASJ1jC4cXtQriE0ZRVZG3DdXZPyd5D1jtxDBg42+kI9OGxkQO0N4zPpsYgGRkYF8VlR3zImEB3Jw9FCo0wCFKwRA2wGSec8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
